apiVersion: v1
kind: Service
metadata:
  name: tubearchivist
  labels:
    app: tubearchivist
spec:
  ports:
    - port: 8050
      targetPort: 8000
  selector:
    app: tubearchivist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tubearchivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tubearchivist
  template:
    metadata:
      labels:
        app: tubearchivist
    spec:
      containers:
        - name: tubearchivist
          image: bbilly1/tubearchivist
          ports:
            - containerPort: 8000
          env:
            - name: ES_URL
              value: http://archivist-es:9200
            - name: REDIS_HOST
              value: archivist-redis
            - name: TA_HOST
              value: tubearchivist.myhomelab.fr
            - name: HOST_UID
              value: "1000"
            - name: HOST_GID
              value: "1000"
            - name: TA_USERNAME
              value: rloyaute
            - name: TA_PASSWORD
              value: BdFjuaLRMj2Y3Z
            - name: ELASTIC_PASSWORD
              value: BdFjuaLRMj2Y3Z
            - name: TZ
              value: Europe/Paris
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "250m"
          volumeMounts:
            - name: media
              mountPath: /youtube
            - name: cache
              mountPath: /cache
      volumes:
        - name: media
          hostPath:
            path: /mnt/youtube-dl/tubearchivist-media
        - name: cache
          hostPath:
            path: /mnt/youtube-dl/tubearchivist-cache
---
apiVersion: v1
kind: Service
metadata:
  name: archivist-redis
  labels:
    app: archivist-redis
spec:
  ports:
    - port: 6379
  selector:
    app: archivist-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivist-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivist-redis
  template:
    metadata:
      labels:
        app: archivist-redis
    spec:
      containers:
        - name: archivist-redis
          image: redislabs/rejson
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "250m"
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
          hostPath:
            path: /mnt/youtube-dl/tubearchivist-redis
---
apiVersion: v1
kind: Service
metadata:
  name: archivist-es
  labels:
    app: archivist-es
spec:
  ports:
    - port: 9200
  selector:
    app: archivist-es
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivist-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivist-es
  template:
    metadata:
      labels:
        app: archivist-es
    spec:
      containers:
        - name: archivist-es
          image: bbilly1/tubearchivist-es
          ports:
            - containerPort: 9200
          env:
            - name: ELASTIC_PASSWORD
              value: BdFjuaLRMj2Y3Z
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: xpack.security.enabled
              value: "true"
            - name: discovery.type
              value: single-node
            - name: path.repo
              value: /home/rloyaute/tubearchivist/elasticsearch/data/snapshot
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "250m"
          volumeMounts:
            - name: es
              mountPath: /home/rloyaute/tubearchivist/elasticsearch/data
      volumes:
        - name: es
          hostPath:
            path: /mnt/youtube-dl/tubearchivist-es
