apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone-backend
  namespace: youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-clone-backend
  template:
    metadata:
      labels:
        app: youtube-clone-backend
    spec:
      containers:
        - name: server
          image: reeeeegis/youtube-clone-nodejs-api-backend:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: uploads
              mountPath: /uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-backend
  namespace: youtube
spec:
  selector:
    app: youtube-clone-backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: LoadBalancer
  loadBalancerIP: 10.100.10.32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone-frontend
  namespace: youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-clone-frontend
  template:
    metadata:
      labels:
        app: youtube-clone-frontend
    spec:
      containers:
        - name: frontend
          image: reeeeegis/youtube-clone-vue-nodejs-frontend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-frontend
  namespace: youtube
spec:
  selector:
    app: youtube-clone-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.100.10.33

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  namespace: youtube
  labels:
    app: youtube-clone-backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
