apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-env
data:
  .env: |
    MYSQL_DATABASE=<value>
    MYSQL_USER=<value>
    MYSQL_PASSWORD=<value>
    MYSQL_HOSTNAME=<value>
    GUACD_HOSTNAME=guacd
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
spec:
  selector:
    app: guacd
  ports:
    - name: guacd-port
      port: 4822
      targetPort: 4822
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - name: guacamole-port
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd
          envFrom:
            - configMapRef:
                name: guacamole-env
          ports:
            - containerPort: 4822
          volumeMounts:
            - name: guacd-config
              mountPath: /etc/guacd
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole
          envFrom:
            - configMapRef:
                name: guacamole-env
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: guacamole-config
              mountPath: /etc/guacamole

//This manifest creates a ConfigMap to store the environment variables defined in the .env file, two Services to expose the ports for the guacd and guacamole containers, and two Deployments to define the details of the guacd and guacamole containers such as the image, environment variables, ports, and volume mounts.

Please note that the environment variables should be replaced by the appropriate values for your setup and that you may need to adjust the volume mounts to match your specific configuration.