apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: youtube
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: backend
    spec:
      tolerations:
        - operator: Exists
      nodeSelector:
        node-role.k3s.io/worker: ""
      containers:
      - name: mongo
        image: mongo:latest
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: youtube
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  type: LoadBalancer
  loadBalancerIP: 10.100.10.34
