apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
      - name: npm
        image: jc21/nginx-proxy-manager:latest
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        env:
        - name: LOCAL_NETWORK
          value: "10.100.0.0/16"
        - name: TZ
          value: Europe/Paris
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config-volume
          mountPath: /data/
        - name: downloads-volume
          mountPath: /etc/letsencrypt/
      volumes:
        - name: config-volume
          nfs:
            server: truenas
            path: /mnt/piscine/files/media/youtube-dl/npm-config
        - name: downloads-volume
          nfs:
            server: truenas
            path: /mnt/piscine/files/media/youtube-dl/npm-downloads