apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
      - name: npm
        image: jc21/nginx-proxy-manager:latest
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        env:
        - name: LOCAL_NETWORK
          value: "10.100.0.0/16"
        volumeMounts:
        - name: data
          mountPath: /data/
        - name: letsencrypt
          mountPath: /etc/letsencrypt/
      volumes:
        - name: data
          hostPath:
            path: /mnt/data
        - name: letsencrypt
          hostPath:
            path: /mnt/letsencrypt
